modLoader="javafml"

loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="bioplethora"
version="${file.jarVersion}"
displayName="Bioplethora"
authors="AquTheSeal, Sajevius, SeagullBoi, Sonic-3xn40s"
logoFile="bplogo.png"
description='''
A minecraft mod that adds plenty of new content which mainly focuses on new creatures and terrifying beasts! Varying from small tamable partners, to colossal eldritch demons. All balanced and wonderful!
'''

[[dependencies.bioplethora]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.bioplethora]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"

[[dependencies.bioplethora]]
modId="geckolib3"
mandatory=true
versionRange="[3.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.bioplethora]]
modId="patchouli"
mandatory=false
versionRange="[1.16-42,)"
ordering="NONE"
side="BOTH"

[[dependencies.bioplethora]]
modId="fabric-biome-api"
mandatory=true
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"